const { cmd } = require("../command");
const axios = require("axios");
const fs = require("fs");

async function generateAIImage(conn, m, { q, reply }, apiEndpoint, captionPrefix) {
    try {
        if (!q) return reply("Please provide a prompt for the image.");

        await reply("> *CREATING IMAGINE ...🔥*");

        const apiUrl = `${apiEndpoint}?prompt=${encodeURIComponent(q)}`;
        const response = await axios.get(apiUrl, { responseType: "arraybuffer" });

        if (!response || !response.data) {
            return reply("Error: The API did not return a valid image. Try again later.");
        }

        const imageBuffer = Buffer.from(response.data, "binary");

        await conn.sendMessage(m.chat, {
            image: imageBuffer,
            caption: `${captionPrefix}\n✨ Prompt: *${q}*`
        });

    } catch (error) {
        console.error("AI Image Error:", error);
        reply(`An error occurred: ${error.response?.data?.message || error.message || "Unknown error"}`);
    }
}

// FluxAI
cmd({
    pattern: "fluxai",
    alias: ["flux", "imagine"],
    react: "🚀",
    desc: "Generate an image using AI.",
    category: "main",
    filename: __filename
}, (conn, mek, m, args) => generateAIImage(conn, m, args, "https://api.siputzx.my.id/api/ai/flux", "💸 *Imagine Generated By ×º𝓑𝖔𝙨𝙨º×* 🚀"));

// Stable Diffusion
cmd({
    pattern: "stablediffusion",
    alias: ["sdiffusion", "imagine2"],
    react: "🚀",
    desc: "Generate an image using AI.",
    category: "main",
    filename: __filename
}, (conn, mek, m, args) => generateAIImage(conn, m, args, "https://api.siputzx.my.id/api/ai/stable-diffusion", "💸 *Imagine Generated BY ﮩ٨ـﮩﮩ٨ـ 𝑩𝑶𝑺𝑺ﮩ٨ـﮩﮩ٨ـ* 🚀"));

// StabilityAI
cmd({
    pattern: "stabilityai",
    alias: ["stability", "imagine3"],
    react: "🚀",
    desc: "Generate an image using AI.",
    category: "main",
    filename: __filename
}, (conn, mek, m, args) => generateAIImage(conn, m, args, "https://api.siputzx.my.id/api/ai/stabilityai", "💸 *Imagine Generated BY 🔥🥀𝘽οꜱꜱ🥀🔥*🚀"));
